[package]
name = "road_loader"
version = "0.1.0"
edition = "2024"

[dependencies.windows]
version = "0.61.1"
features = [
    "Win32_Foundation",
    "Win32_System_ClrHosting",
    "Win32_System_Com",
]