name: msbuild
permissions:
  contents: write

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: cargo build --release

      - name: test exec
        run: ./target/release/road_loader.exe -p .\.net4-test-project.exe -- "argument"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            ./target/release/road_loader.exe
